# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bquery.proto\x12\x05query\"/\n\x0cResponseBody\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x05\"\x1e\n\x0bRequestBody\x12\x0f\n\x07message\x18\x01 \x01(\t2I\n\x0fResponseService\x12\x36\n\x0bGetResponse\x12\x12.query.RequestBody\x1a\x13.query.ResponseBodyB\nZ\x08pb/queryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'query_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\010pb/query'
  _globals['_RESPONSEBODY']._serialized_start=22
  _globals['_RESPONSEBODY']._serialized_end=69
  _globals['_REQUESTBODY']._serialized_start=71
  _globals['_REQUESTBODY']._serialized_end=101
  _globals['_RESPONSESERVICE']._serialized_start=103
  _globals['_RESPONSESERVICE']._serialized_end=176
# @@protoc_insertion_point(module_scope)
